### ***Broadcasting & Vectorization in NumPy***

In [ ]:
import numpy as np

In [ ]:
# write a program to add two different python lists -
# li1 = [1,2,3,4]
# li2 = [5,6,7,8]

# res_li = []

# for ind in range(0, 4):
#   res_li.append(li1[ind] + li2[ind])

# print(res_li)


# write a program to add two different python (NumPy) Arrays -
# arr1 = np.array([1,2,3,4])
# arr2 = np.array([5,6,7,8])

# res_arr = arr1 + arr2     # Vectorization - performing operatios on entire arrays at once without using python loops
# print(res_arr)


# _2DArr1 = np.arange(1,13).reshape(3,4)
# print(_2DArr1)
# _1DArr2 = np.arange(13,15)
# print(_1DArr2)

# resArr = _2DArr1 + _1DArr2
# print(resArr)

# Broadcasting -

# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]

# [[13 14 15 16]
# [13 14 15 16]
# [13 14 15 16]]

# arr = np.arange(1,7)
# print(arr)
# newArr = arr + 7

# print(newArr)

# ***Handling Missing & Infinite Numerical Values in NumPy***

In [ ]:
# arr = np.array([np.nan,20,np.nan,40,np.nan,60])
# print(arr)

# print(np.isnan(arr))
# print(np.isnan(arr).sum())

# np.nan_to_num(arr, nan=30)


# infArr = np.array([10,np.inf,30,-np.inf,20,-np.inf])
# print(infArr)

# print(np.nan_to_num(infArr, posinf=25, neginf=-25))

[ 10.  inf  30. -inf  20. -inf]
[10. 25. 30. 25. 20. 25.]
