### ***Slicing an array in NumPy***

In [2]:
import numpy as np

In [23]:
# arr = np.arange(1, 13)
# print(arr)

# slicing - array[start:end:skip] - 1D Array
# newArr = arr[4:10:2]
# newArr = arr[0:len(arr)]
# print(newArr)
# newArr[0] = 145
# print(arr)
# print(newArr)

# newArr = arr[:]
# print(newArr)
# newArr[0] = 145
# print(arr)
# print(newArr)

# newArr = arr[:10]
# print(newArr)

# newArr = arr[4:]
# print(newArr)

# newArr = arr[::-1]
# print(newArr)

# newArr = arr[9:1:-1]
# print(newArr)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[10  9  8  7  6  5  4  3]


In [74]:
# 2D Array Slicing -

# arr = np.random.rand(10)*10
# print(arr.astype(np.int64))

# arr = np.random.randint(5,10)
# print(arr)

# _2Darr = np.arange(1,25).reshape(3,8)
# print(_2Darr)
# midArr = _2Darr[0::2]
# print(midArr)
# newarr = _2Darr[1::-1]
# print(newarr)

# 2D-Slicing - array[start:end:skip, start:end:skip] ---> array[row, column]

# newArr = _2Darr[:,2].reshape(3, 1)
# print(newArr)

# newArr = _2Darr[1:, 3:1:-1]
# print(newArr)

[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]
 [17 18 19 20 21 22 23 24]]
[[12 11]
 [20 19]]


In [84]:
_2Darr = np.arange(1,25).reshape(2,3,4)
print(_2Darr)

# 3D Slicing - array[start:end:skip, start:end:skip, start:end:skip]
            #  array[     page     ,      row      ,     column    ]

# newArr = _2Darr[0, :, 3].reshape(3,1)
# print(newArr)

# newArr = _2Darr[1, :, 1:]
# print(newArr)

# newArr = _2Darr[:, 1, 1:3]
# print(newArr)

# newArr = [_2Darr[0, 1, 1:3], _2Darr[1, 2, 2:]]
# print(newArr)
# naweArr = np.array(newArr)
# print(naweArr)



[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]
[array([6, 7]), array([23, 24])]
[[ 6  7]
 [23 24]]
