### ***Pre-Built Methods in NumPy***

In [1]:
import numpy as np

In [43]:
# arr = np.array([4,5,8,7,6,9,2])
# arr[-7]
# arr[3]
# print(f"Before Changing - {arr}")
# Fancy Indexing -
# newArr = arr[[0, 2, 4, 5]]
# print(f"Before Changing - {newArr}")

# newArr[3] = 58

# print(f"After Changing - {newArr}")
# print(f"After Changing - {arr}")


# Boolean Masking - it will provide a filtered array on the basis of certain conditions
# arr = np.array([4,5,8,7,6,9,2])
# # newArr = arr[arr%2 == 0]
# newArr = arr[arr > 7]
# print(f"Org Array - {arr}")
# print(f"Filtered Array - {newArr}")
# newArrReshaped = newArr.reshape(2,1)
# newArrReshaped



# Slicing in NumPy -
# arr = np.array([4,5,8,7,6,9,2,4])
# print(arr)

# slicedArr = arr[0:5:1]
# print(slicedArr)

# slicedArr1 = arr[2:8:2]
# print(slicedArr1)

# negSlicedArr = arr[-1:-5:-2]
# print(negSlicedArr)

# empSlicing = arr[:]
# print(empSlicing)

# revArr = arr[::-2]
# print(revArr)
# print(arr)





# Type-Casting in NumPy - there are two ways to type cast an array in NumPy
fullArr = np.full([4,4], 4, dtype=np.float64)
print(fullArr)

shallowFullArr = fullArr.astype(np.int64)
print(shallowFullArr)

shallowFullArr[0] = [1,2,3,4]
print(shallowFullArr)
print(fullArr)
print(shallowFullArr)

[[4. 4. 4. 4.]
 [4. 4. 4. 4.]
 [4. 4. 4. 4.]
 [4. 4. 4. 4.]]
[[4 4 4 4]
 [4 4 4 4]
 [4 4 4 4]
 [4 4 4 4]]
[[1 2 3 4]
 [4 4 4 4]
 [4 4 4 4]
 [4 4 4 4]]
[[4. 4. 4. 4.]
 [4. 4. 4. 4.]
 [4. 4. 4. 4.]
 [4. 4. 4. 4.]]
[[1 2 3 4]
 [4 4 4 4]
 [4 4 4 4]
 [4 4 4 4]]
