### ***More pre-built Methods in NumPy***

In [1]:
import numpy as np

In [57]:
from re import U
# np.append() - it will insert an element in the array as well as it will create a shallow copied array!
# arr  = np.arange(12)
# print(arr)

# newArr = np.append(arr, [12,13,14,15])
# print(newArr)

# 2D Array -
# arr  = np.arange(12).reshape(3,4)
# print(arr)

# newArr = np.append(arr, [[12,13,14,15], [16,17,18,19], [20,21,22,23]])      #  with 2 arguments it will return a 1D Array
# print(newArr)

# newArr = np.append(arr, [[12,13,14,15], [16,17,18,19], [20,21,22,23]], 1)      #  with 3 arguments it will return a 2D Array based on 0 or 1 axis    |    0 - Row    &    1 - column
# print(newArr)


# 3D Array - this must be done by Raksharaj by today!







# np.insert()
# arr  = np.arange(12)
# print(arr)

# newArr = np.insert(arr, 4, [45, 42,40], 0)    # np.insert(array, index, Value, Axis)
# print(newArr)

# 2D and 3D Array practice must be done by Raksharaj by today only!




# np.delete()
# arr  = np.arange(1, 12)
# print(arr)

# newArr = np.delete(arr, [4, 6, 8])
# print(newArr)

# 2D and 3D Array practice must be done by Raksharaj by today only!


# C - Creation of Data
# R - Reading of Data
# U - Updation of Data
# D - Deletion of Data

# CRUD Operation - is a process or operation in which we will manipulate the Data by creating, reading, updating and deleting the data


# arr = np.arange(1,28).reshape(3,3,3)
# # print(arr)

# flattenArr = arr.flatten()
# print(flattenArr)
# flattenArr[5] = 154
# print(f"flatten array using flatten method - {flattenArr}")     # this will create a shallow copied flat array
# print(arr)

# ravelArr = arr.ravel()
# print(ravelArr)
# ravelArr[5] = 154
# print(f"flatten array using ravel method - {ravelArr}")     # this will create a Deep copied flat array
# print(arr)

# ***Aggregation methods in NumPy***

In [74]:
# Aggregation method - it will provide a statistical summary of the array or data on which we used them

# sum
# mean
# median
# average
# min
# max
# std


# arr = np.arange(1,28).reshape(9,3)
# print(arr)

# arraySum = np.sum(arr)

arr1 = np.arange(1,13).reshape(3, 4)
print(arr1)

arr2 = np.arange(13,25).reshape(3, 4)
print(arr2)

# arr = arr1 + arr2
# print(arr)

# resultArr = np.sum([arr1, arr2])
# print(resultArr)
# print(f"sum is - {arraySum}")
# arrayMean = np.mean(arr1)
# print(f"mean is - {arrayMean}")
# arrayMedian = np.median(arr1)
# print(f"median is - {arrayMedian}")
# arrayMin = np.min()
# print(f"min value is - {arrayMin}")
# arrayMax = np.max()
# print(f"max value is - {arrayMax}")
# arrayAverage = np.average()
# print(f"average value is - {arrayAverage}")
# arrayStd = np.std()
# print(f"standard deviation is - {arrayStd}")


[ 1  2  3  4  5  6  7  8  9 10 11 12 13]
[[13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]
median is - 7.0
