### ***Difference Python List VS Numpy Array***

In [6]:
import time as tl
import numpy as np

In [7]:
# Python list -
# short list -
# li = []
# for value in range(1, 11):
#   li.append(value)

# print(li)


# large list -
# li = []
# start_time = tl.time()
# for value in range(1, 100000):
#   li.append(value)

# end_time = tl.time()
# op_time = end_time - start_time
# print(op_time)

In [8]:
# st_time = tl.time()
# numArr = np.arange(1, 100000)
# ed_time = tl.time()
# opt_time = ed_time - st_time
# print(opt_time)

### ***Creating n-dim NumPy Arrays***

In [26]:
# li = [1,2,3,4]
# tup = (5,6,7,8)
# st = {9,8,7,6}

# liArr = np.array(li)
# tupArr = np.array(tup)
# setArr = np.array(st)

# liArr, tupArr, setArr

# print(liArr)
# print(tupArr)
# print(setArr)


# ---> 1D-array -
# arr = np.array([10,40,50,80,20,60])
# print(arr)
# np.ndim(arr)


# ---> 2D-array -
# _2dArray = np.array([[1,2,3,4]])
# print(_2dArray)
# np.ndim(_2dArray)


# ---> 2D-array with rows and columns -
# _2dArray = np.array([
#             [1,2,3,4],
#             [5,6,7,8],
#             [9,8,7,5]
#           ])
# print(_2dArray)
# print(np.ndim(_2dArray))
# print(np.shape(_2dArray))


# ---> 3D-array with rows and columns -
# _3dArray = np.array([
#     [
#             [1,2,3,4],
#             [5,6,7,8],
#             [9,8,7,5]
#     ],
#     [
#             [1,2,3,4],
#             [5,6,7,8],
#             [9,8,7,5]
#     ],
#     [
#             [1,2,3,4],
#             [5,6,7,8],
#             [9,8,7,5]
#     ]


#     ])
# print(_3dArray)
# print(np.ndim(_3dArray))
# print(np.shape(_3dArray))


[[[1 2 3 4]
  [5 6 7 8]
  [9 8 7 5]]

 [[1 2 3 4]
  [5 6 7 8]
  [9 8 7 5]]

 [[1 2 3 4]
  [5 6 7 8]
  [9 8 7 5]]]
3
(3, 3, 4)


### ***Performing Indexing n-dim NumPy Arrays***

In [36]:
# ---> 1D-array -
# arr = np.array([10,40,50,80,20,60])
# print(arr[0])
# print(arr[1])
# print(arr[2])
# print(arr[3])
# print(arr[4])
# print(arr[5])

# ---> 2D-array -
# _2dArray = np.array([[1,2,3,4]])
# print(_2dArray)
# np.ndim(_2dArray)


# ---> 2D-array with rows and columns -
_2dArray = np.array([
            [1,2,3,4],
            [5,6,7,8],
            [9,8,7,5]
          ])

# print(_2dArray[0][0])
# print(_2dArray[0][1])
# print(_2dArray[0][2])
# print(_2dArray[0][3])

# print(_2dArray[1][0])
# print(_2dArray[1][1])
# print(_2dArray[1][2])
# print(_2dArray[1][3])

# print(_2dArray[2][0])
# print(_2dArray[2][1])
# print(_2dArray[2][2])
# print(_2dArray[2][3])

# print(_2dArray[0])
# print(_2dArray[1])
# print(_2dArray[2])



# ---> 3D-array with rows and columns -
# _3dArray = np.array([
#       [
#             [1,2,3,4],
#             [5,6,7,8],        # page - 1
#             [9,8,7,5]
#       ],
#       [
#             [1,2,3,4],
#             [5,6,7,8],        # page - 2
#             [9,8,7,5]
#       ],
#       [
#             [1,2,3,4],
#             [5,6,7,8],        # page - 3
#             [9,8,7,5]
#       ]
#     ])
# print(_3dArray)
# print(np.ndim(_3dArray))
# print(np.shape(_3dArray))


1
2
3
4
5
6
7
8
9
8
7
5
